// This is a fork of SpeedBridge https://www.spigotmc.org/resources/speedbridge-1-free-bridge-trainer-ending-support-at-1-4-2022.95918/
name: xBridge
version: ${project.version}
main: me.tofpu.speedbridge.SpeedBridge
api-version: 1.13
authors: [ SrMaster ]
softdepend:
  - PlaceholderAPI
  speedbridge:
commands:
