settings:
  # if true, you will get teleported to the lobby upon joining
  # if false, you won't get teleported to the lobby upon joining
  teleport: true

mode:
  default: hard
  list:
    standard: 0-10
    hard: 11-20